/**
 * Reads drizzle-kit output (drizzle/meta/_journal.json + *.sql) and writes
 * src/db/migrations.generated.ts so migrations ship inside the JS bundle.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const journal = JSON.parse(readFileSync(join(root, 'drizzle/meta/_journal.json'), 'utf8')) as {
  entries: { idx: number; when: number; tag: string; breakpoints: boolean }[];
};

const migrations = journal.entries.map((e) => {
  const sql = readFileSync(join(root, 'drizzle', `${e.tag}.sql`), 'utf8');
  const statements = sql
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter(Boolean);
  return { tag: e.tag, when: e.when, hash: createHash('sha256').update(sql).digest('hex'), sql: statements };
});

const out = `// AUTO-GENERATED by scripts/bundle-migrations.ts. Do not edit.
export interface EmbeddedMigration { tag: string; when: number; hash: string; sql: string[] }
export const MIGRATIONS: EmbeddedMigration[] = ${JSON.stringify(migrations, null, 2)};
`;
writeFileSync(join(root, 'src/db/migrations.generated.ts'), out);
console.log(`bundled ${migrations.length} migration(s)`);
