// AUTO-GENERATED by scripts/bundle-migrations.ts. Do not edit.
export interface EmbeddedMigration { tag: string; when: number; hash: string; sql: string[] }
export const MIGRATIONS: EmbeddedMigration[] = [
  {
    "tag": "0000_lyrical_starfox",
    "when": 1789530253232,
    "hash": "3af11eb3c8d21a43ed6b01bb56748f913f6a233b4009d9fa7c40990eb5f836be",
    "sql": [
      "CREATE TABLE `attempts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`task_id` text NOT NULL,\n\t`executor` text NOT NULL,\n\t`branch` text NOT NULL,\n\t`worktree_path` text NOT NULL,\n\t`base_commit` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`pr_url` text,\n\t`last_test_output` text,\n\t`last_test_ok` integer,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `attempts_task_idx` ON `attempts` (`task_id`);",
      "CREATE TABLE `comments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`task_id` text NOT NULL,\n\t`attempt_id` text,\n\t`kind` text NOT NULL,\n\t`body` text NOT NULL,\n\t`file_path` text,\n\t`line` integer,\n\t`consumed_by_run_id` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`attempt_id`) REFERENCES `attempts`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`consumed_by_run_id`) REFERENCES `runs`(`id`) ON UPDATE no action ON DELETE set null\n);",
      "CREATE INDEX `comments_task_idx` ON `comments` (`task_id`);",
      "CREATE TABLE `jobs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`kind` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`status` text DEFAULT 'queued' NOT NULL,\n\t`attempts_count` integer DEFAULT 0 NOT NULL,\n\t`locked_by` text,\n\t`run_after` text NOT NULL,\n\t`error` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE INDEX `jobs_status_idx` ON `jobs` (`status`,`run_after`);",
      "CREATE TABLE `projects` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`repo_path` text NOT NULL,\n\t`default_executor` text DEFAULT 'claude' NOT NULL,\n\t`base_branch` text DEFAULT 'main' NOT NULL,\n\t`setup_script` text,\n\t`test_script` text,\n\t`auto_done` integer DEFAULT false NOT NULL,\n\t`refinement_enabled` integer DEFAULT true NOT NULL,\n\t`max_concurrent_runs` integer DEFAULT 2 NOT NULL,\n\t`run_timeout_minutes` integer DEFAULT 45 NOT NULL,\n\t`refinement_prompt` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
      "CREATE UNIQUE INDEX `projects_repo_path_unique` ON `projects` (`repo_path`);",
      "CREATE TABLE `refinement_questions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`task_id` text NOT NULL,\n\t`run_id` text NOT NULL,\n\t`question` text NOT NULL,\n\t`answer` text,\n\t`created_at` text NOT NULL,\n\t`answered_at` text,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`run_id`) REFERENCES `runs`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `refinement_questions_task_idx` ON `refinement_questions` (`task_id`);",
      "CREATE TABLE `run_events` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`run_id` text NOT NULL,\n\t`seq` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`payload` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`run_id`) REFERENCES `runs`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `run_events_run_seq_idx` ON `run_events` (`run_id`,`seq`);",
      "CREATE TABLE `runs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`attempt_id` text,\n\t`task_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`executor` text NOT NULL,\n\t`prompt` text NOT NULL,\n\t`command` text,\n\t`status` text DEFAULT 'queued' NOT NULL,\n\t`exit_code` integer,\n\t`session_id` text,\n\t`resumed_from_session_id` text,\n\t`result_subtype` text,\n\t`structured_output` text,\n\t`cost_usd` real,\n\t`num_turns` integer,\n\t`error_message` text,\n\t`started_at` text,\n\t`finished_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`attempt_id`) REFERENCES `attempts`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `runs_task_idx` ON `runs` (`task_id`);",
      "CREATE INDEX `runs_attempt_idx` ON `runs` (`attempt_id`);",
      "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text DEFAULT '' NOT NULL,\n\t`column` text DEFAULT 'backlog' NOT NULL,\n\t`substate` text,\n\t`position` real DEFAULT 0 NOT NULL,\n\t`executor` text,\n\t`skip_refinement` integer DEFAULT false NOT NULL,\n\t`plan` text,\n\t`refinement_session_id` text,\n\t`refinement_incomplete` integer DEFAULT false NOT NULL,\n\t`current_attempt_id` text,\n\t`last_error` text,\n\t`source_provider` text,\n\t`source_external_id` text,\n\t`source_url` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `tasks_project_column_idx` ON `tasks` (`project_id`,`column`);"
    ]
  },
  {
    "tag": "0001_crazy_night_thrasher",
    "when": 1789535931110,
    "hash": "24ab4f51ec493fd2444a5d57a9e9213857c10858eb10e9661253168886730e34",
    "sql": [
      "ALTER TABLE `runs` ADD `result_text` text;"
    ]
  },
  {
    "tag": "0002_reflective_the_stranger",
    "when": 1789537778350,
    "hash": "51c1c0e0caf16c54aae0b93e6ca25d9a1e24ad4b95847acc1aa4cc3b02ce1fe3",
    "sql": [
      "ALTER TABLE `projects` ADD `model` text;",
      "ALTER TABLE `projects` ADD `max_budget_usd` real;",
      "ALTER TABLE `projects` ADD `prompt_language` text DEFAULT 'vi' NOT NULL;",
      "ALTER TABLE `projects` ADD `execute_prompt` text;",
      "ALTER TABLE `projects` ADD `followup_prompt` text;",
      "ALTER TABLE `projects` ADD `done_action` text DEFAULT 'merge' NOT NULL;",
      "ALTER TABLE `runs` ADD `pid` integer;",
      "ALTER TABLE `runs` ADD `log_dir` text;",
      "ALTER TABLE `runs` ADD `fallback_of_run_id` text;",
      "ALTER TABLE `tasks` ADD `model` text;"
    ]
  },
  {
    "tag": "0003_dashing_dorian_gray",
    "when": 1789541586941,
    "hash": "d84c04ae86b292aedd1038d9f253ac3ca40f07213d332fef6093bcdfedcad4a0",
    "sql": [
      "CREATE TABLE `attachments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`comment_id` text NOT NULL,\n\t`task_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`mime` text NOT NULL,\n\t`size` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`comment_id`) REFERENCES `comments`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `attachments_comment_idx` ON `attachments` (`comment_id`);",
      "ALTER TABLE `projects` ADD `auto_start` integer DEFAULT false NOT NULL;"
    ]
  },
  {
    "tag": "0004_nebulous_talkback",
    "when": 1789543391278,
    "hash": "6a5fdb5a782b32a004deb115b4de52b828866451d2918444ecc1a13ff262ea7c",
    "sql": [
      "ALTER TABLE `projects` ADD `browser_enabled` integer DEFAULT false NOT NULL;",
      "ALTER TABLE `tasks` ADD `browser` integer;"
    ]
  },
  {
    "tag": "0005_exotic_sharon_carter",
    "when": 1789543827738,
    "hash": "315fb5666d7a86f9bc81a4074a481cc266455c7d443bfaf25e646bce35fd7481",
    "sql": [
      "ALTER TABLE `jobs` ADD `priority` integer DEFAULT 0 NOT NULL;",
      "ALTER TABLE `projects` ADD `issue_sync` integer DEFAULT true NOT NULL;",
      "ALTER TABLE `projects` ADD `issue_import_labels` text;",
      "ALTER TABLE `projects` ADD `issue_provider` text;",
      "ALTER TABLE `projects` ADD `issue_project_ref` text;",
      "ALTER TABLE `tasks` ADD `kind` text;",
      "ALTER TABLE `tasks` ADD `priority` text;"
    ]
  },
  {
    "tag": "0006_heavy_lethal_legion",
    "when": 1789545063400,
    "hash": "dc5833f4e12cc6f04a54c26d0b952580977704a0c7beba1942bc789a3183821c",
    "sql": [
      "CREATE TABLE `integrations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`base_url` text,\n\t`project_ref` text NOT NULL,\n\t`auth` text NOT NULL,\n\t`import_filter` text,\n\t`status_map` text NOT NULL,\n\t`sync_status` integer DEFAULT true NOT NULL,\n\t`sync_comments` integer DEFAULT true NOT NULL,\n\t`poll_interval_seconds` integer DEFAULT 30 NOT NULL,\n\t`last_polled_at` text,\n\t`last_error` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `integrations_project_id_unique` ON `integrations` (`project_id`);",
      "ALTER TABLE `projects` DROP COLUMN `issue_sync`;",
      "ALTER TABLE `projects` DROP COLUMN `issue_import_labels`;",
      "ALTER TABLE `projects` DROP COLUMN `issue_provider`;",
      "ALTER TABLE `projects` DROP COLUMN `issue_project_ref`;"
    ]
  }
];
